version: '3.8'
services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - web
      - dns
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "81:80/tcp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
